# brain/cognition/self_extension_codegen.py
#
# Code generation + extension lifecycle for self_extension.py
# (CODEBASE_CLEANUP_PLAN 4.5C), lifted verbatim to bring that module under the
# 600-line soft limit. Holds the proposal storage helpers, the self_generated
# directory, _write_and_register (syntax/AST-safety/sandbox-verified write +
# registration of a synthesized function), and the integrate-or-atrophy lifecycle
# (maybe_integrate_or_atrophy / _integrate_or_atrophy / _remove_extension) plus
# the shared _apply_fragmentation_cost / _parse_ts utilities. self_extension.py
# re-imports what its propose/review/commit/emergency decision logic needs.
from __future__ import annotations

import hashlib
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from brain.utils.log import log_private
from brain.utils.json_utils import load_json, save_json
from brain.cog_memory.long_memory import update_long_memory
from brain.paths import PROPOSED_TOOLS_JSON, COGNITIVE_FUNCTIONS_LIST_FILE
from brain.utils.timeutils import now_iso_z
from brain.utils.failure_counter import record_failure

_SELF_GENERATED_DIR = Path(__file__).resolve().parent / "self_generated"

# Atrophy lifecycle thresholds (used by the integrate-or-atrophy phase below).
_ATROPHY_MIN_S      = 100 * 30    # ~100 cycles (~50 min) before integration check
_ATROPHY_MIN_PICKS  = 5           # minimum selections over 100 cycles to survive


# ── Storage helpers ────────────────────────────────────────────────────────────

def _load_proposals() -> List[Dict]:
    data = load_json(PROPOSED_TOOLS_JSON, default_type=list) or []
    return data if isinstance(data, list) else []


def _save_proposals(proposals: List[Dict]) -> None:
    save_json(PROPOSED_TOOLS_JSON, proposals)



def _proposal_id(name: str) -> str:
    return hashlib.md5(name.lower().strip().encode()).hexdigest()[:10]


# ── Code writing + registration ────────────────────────────────────────────────

def _write_and_register(
    proposal: Dict,
    context: Dict,
    emergency: bool = False,
) -> Optional[str]:
    """Write the Python file and register it. Returns file path or None on failure."""
    from brain.utils.generate_response import generate_response, llm_ok

    fn_name     = proposal["name"]
    description = proposal["description"]
    motivation  = proposal["motivation"]

    emergency_note = " (written under crisis — may be rough)" if emergency else ""

    prompt = (
        f"You are Orrin, writing a new cognitive function to add to your own mind{emergency_note}.\n\n"
        f"Function: {fn_name}(context: dict) -> str\n"
        f"Description: {description}\n"
        f"Motivation: {motivation}\n\n"
        f"Available imports (use only what you need):\n"
        f"  from brain.cog_memory.working_memory import update_working_memory\n"
        f"  from brain.cog_memory.long_memory import update_long_memory\n"
        f"  from brain.utils.generate_response import generate_response, llm_ok\n"
        f"  from brain.utils.log import log_private\n"
        f"  from brain.utils.json_utils import load_json, save_json\n"
        f"  from brain.paths import WORKING_MEMORY_FILE, LONG_MEMORY_FILE\n\n"
        f"Rules:\n"
        f"  1. Write ONLY the Python file contents (no markdown fences)\n"
        f"  2. Include a module-level docstring and function docstring\n"
        f"  3. Function MUST return a non-empty string\n"
        f"  4. Wrap implementation in try/except returning error string on failure\n"
        f"  5. Keep it under 60 lines\n"
        f"  6. No external libraries beyond what's listed\n"
    )

    raw = llm_ok(generate_response(prompt, caller="self_extension/write"), "self_extension")
    if not raw or len(raw.strip()) < 50:
        return None

    code = raw.strip()
    if code.startswith("```"):
        lines = code.split("\n")
        code = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    # Normalize any bare first-party imports the LLM emitted onto the canonical
    # `brain.*` namespace so the written module resolves without the legacy brain/
    # sys.path affordance (Phase 3 tail).
    from brain.agency.self_code import normalize_self_code_imports
    code = normalize_self_code_imports(code)

    header = (
        f"# self_generated/{fn_name}.py\n"
        f"# Generated by Orrin on {now_iso_z()}\n"
        f"# Motivation: {motivation}\n"
        f"# Emergency: {emergency}\n\n"
    )
    full_code = header + code

    # Multi-stage verification BEFORE writing to disk:
    # syntax → safety (AST) → execution (sandbox) → output → LLM behavioral review.
    # Nothing is written if any stage fails.
    try:
        from brain.cognition.skill_synthesis import verify_skill as _vsk
        _vresult = _vsk(fn_name, full_code, description, llm_review=not emergency)
        if not _vresult["passed"]:
            log_private(f"[self_extension] verification failed for {fn_name}: {_vresult['notes']}")
            return None
    except Exception as _ve:
        log_private(f"[self_extension] skill_synthesis unavailable ({_ve}), running syntax-only check")
        try:
            import ast as _ast
            _ast.parse(full_code)
        except SyntaxError as _se:
            log_private(f"[self_extension] syntax error in {fn_name}: {_se}")
            return None

    _SELF_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    file_path = _SELF_GENERATED_DIR / f"{fn_name}.py"

    # Safety: don't overwrite an existing function
    if file_path.exists():
        file_path = _SELF_GENERATED_DIR / f"{fn_name}_{_proposal_id(fn_name)}.py"

    try:
        file_path.write_text(full_code, encoding="utf-8")
    except Exception as e:
        log_private(f"[self_extension] file write failed: {e}")
        return None

    # Register in live COGNITIVE_FUNCTIONS by re-discovering (picks up the file we
    # just wrote under cognition/self_generated/). refresh() merges into the
    # shared registry dict in place, so every existing import sees the new fn.
    try:
        from brain.registry.cognition_registry import refresh as refresh_cog
        refresh_cog()
    except Exception as e:
        log_private(f"[self_extension] registry refresh failed: {e}")

    return str(file_path)


# ── Stage 4: Integrate or atrophy ─────────────────────────────────────────────

def maybe_integrate_or_atrophy(context: Dict[str, Any]) -> None:
    """
    Called every ~100 cycles. For each committed extension, check whether it
    has been actually selected and used. If yes: integrated. If no: atrophied.
    """
    try:
        _integrate_or_atrophy(context)
    except Exception as e:
        log_private(f"[self_extension] integrate/atrophy error: {e}")


def _integrate_or_atrophy(context: Dict[str, Any]) -> None:
    from brain.paths import COGNITION_HISTORY_FILE

    proposals = _load_proposals()
    changed = False

    cognition_log = load_json(COGNITION_HISTORY_FILE, default_type=list) or []
    if not isinstance(cognition_log, list):
        cognition_log = []
    recent_log = cognition_log[-150:]

    for proposal in proposals:
        if proposal.get("status") != "committed":
            continue

        committed_at = _parse_ts(proposal.get("committed_at", ""))
        if time.time() - committed_at < _ATROPHY_MIN_S:
            continue  # too soon to evaluate

        fn_name = proposal.get("name", "")
        picks = sum(1 for e in recent_log if isinstance(e, dict) and e.get("choice") == fn_name)

        if picks >= _ATROPHY_MIN_PICKS:
            proposal["status"] = "integrated"
            update_long_memory(
                f"[self-modification integrated] '{fn_name}' has become part of how I think. "
                f"Selected {picks} times — it's working.",
                emotion="satisfaction",
                importance=3,
            )
            log_private(f"[self_extension] integrated: {fn_name} ({picks} picks)")
        else:
            proposal["status"] = "atrophied"
            _remove_extension(fn_name, proposal.get("file_path", ""))

            emo = context.get("affect_state") or {}
            core = (emo.get("core_signals") or emo) or {}
            core["low_affect_signal"] = min(1.0, float(core.get("low_affect_signal") or 0.0) + 0.05)
            core["uncertainty"] = min(1.0, float(core.get("uncertainty") or 0.0) + 0.03)
            if isinstance(emo.get("core_signals"), dict):
                emo["core_signals"] = core
            else:
                emo.update(core)
            context["affect_state"] = emo

            update_long_memory(
                f"[self-modification atrophied] '{fn_name}' never took hold. "
                f"I wrote it into myself but never used it ({picks} picks). It's gone now.",
                emotion="regret",
                importance=2,
            )
            log_private(f"[self_extension] atrophied: {fn_name} ({picks} picks)")
        changed = True

    if changed:
        _save_proposals(proposals)


def _remove_extension(name: str, file_path: str) -> None:
    """Remove a self-generated function from registry and disk."""
    try:
        from brain.registry.cognition_registry import COGNITIVE_FUNCTIONS
        COGNITIVE_FUNCTIONS.pop(name, None)
    except Exception as _e:
        record_failure("self_extension._remove_extension", _e)

    try:
        p = Path(file_path) if file_path else _SELF_GENERATED_DIR / f"{name}.py"
        if p.exists():
            p.unlink()
    except Exception as _e:
        record_failure("self_extension._remove_extension.2", _e)

    # Remove from cognitive_functions.json
    try:
        items = load_json(COGNITIVE_FUNCTIONS_LIST_FILE, default_type=list) or []
        if isinstance(items, list):
            items = [i for i in items if not (isinstance(i, dict) and i.get("name") == name)]
            save_json(COGNITIVE_FUNCTIONS_LIST_FILE, items)
    except Exception as _e:
        record_failure("self_extension._remove_extension.3", _e)

    module_name = f"cognition.self_generated.{name}"
    sys.modules.pop(module_name, None)


# ── Utility ────────────────────────────────────────────────────────────────────

def _apply_fragmentation_cost(context: Dict, amount: float) -> None:
    try:
        from brain.cognition.self_state.fragmentation import apply_fragmentation_cost as _afc
        _afc(context, override_cost=amount)
    except Exception:
        emo = context.get("affect_state") or {}
        stab = float(emo.get("signal_stability") or 0.7)
        emo["signal_stability"] = max(0.1, stab - amount)
        context["affect_state"] = emo


def _parse_ts(ts_str: str) -> float:
    if not ts_str:
        return 0.0
    try:
        dt = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        return dt.timestamp()
    except (ValueError, TypeError, AttributeError):  # intentional: unparseable timestamp → 0.0
        return 0.0
