# behavior/behavior_generation.py
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from utils.json_utils import load_json, safe_extract_json
from utils.log import log_private, log_error, log_activity
from utils.timeutils import now_iso_z
from utils.generate_response import generate_response, llm_ok
from utils.goals import extract_current_focus_goal
from cognition.behavior import extract_last_reflection_topic
from paths import PROPOSED_GOALS, FOCUS_GOAL, ensure_files

# NOTE (Phase 5 / Option A): this module used to synthesize a Python stub into
# cognition/self_generated/autogenerated_thoughts.py and propose
# execute_python_code to run it. That path is removed — exploratory behavior now
# emits a structured append_thought effect (see generate_behavior_from_integration),
# so no stub file is written and no code is executed.


def _topic_signature(topic: str, context: Dict[str, Any]) -> str:
    # Stable per topic — so we don't re-run 3 LLM calls every cycle for the same goal.
    # Proposals are goal-relative, not cycle-relative. When the topic changes (new goal),
    # the signature changes and behavior generation re-runs.
    return topic

def _coerce_list(x: Any) -> List[str]:
    """Coerce various shapes to a clean list[str]."""
    if isinstance(x, list):
        return [s for s in (v.strip() for v in x if isinstance(v, str)) if s]
    if isinstance(x, dict):
        # Common keys models use
        for k in ("questions", "items", "list", "clarifications", "steps", "tasks"):
            if k in x and isinstance(x[k], list):
                return _coerce_list(x[k])
    if isinstance(x, str):
        # Fallback: split on newlines/bullets
        parts = [p.strip("-• \t") for p in x.splitlines()]
        return [p for p in parts if p]
    return []

def generate_behavior_from_integration(context: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Pure proposal generator. NO side-effects here.
    Returns a list of action dicts for scoring/execution by the action gate.
    Also caches proposals in context to avoid duplicates in the same cycle/topic.
    """

    # Load focus goal into context if missing (read-only)
    if not context.get("focus_goal"):
        try:
            if Path(FOCUS_GOAL).exists():
                context["focus_goal"] = load_json(FOCUS_GOAL, default_type=dict)
        except Exception as e:
            log_error(f"⚠️ Failed to load focus goal from {FOCUS_GOAL}: {e}")

    # 1) Pick a topic
    focus_goal = context.get("focus_goal") or context.get("active_goal")
    topic = (
        extract_current_focus_goal(focus_goal)
        or context.get("last_reflection_topic")
        or extract_last_reflection_topic()
    )

    # Fall back to the active committed goal — the goal he's actually pursuing.
    # Without this, behavior_generation and the goal loop were disconnected:
    # the active goal lived in context["committed_goal"] but this only read
    # focus_goal, so it found no topic and spammed an error every idle cycle.
    if (not topic or not isinstance(topic, str)):
        _cg = context.get("committed_goal")
        if isinstance(_cg, dict):
            topic = _cg.get("title") or _cg.get("name") or ""

    if not topic or not isinstance(topic, str) or not topic.strip():
        # Having nothing to act on is a normal idle state, not an error — log it
        # quietly so it doesn't flood the error log (was firing 6000+ times).
        log_private("[behavior_generation] no actionable topic this cycle — idle")
        return []

    sig = _topic_signature(topic, context)
    if context.get("_behavior_sig") == sig and isinstance(context.get("behavior_proposals"), list):
        # The cached list survives in context.json across restarts, so it can
        # carry a stale "speak" proposal from before the audience gate existed
        # (or from when a user WAS present). Re-apply the gate on every cache
        # hit — announcements never replay to an empty room.
        cached = list(context.get("behavior_proposals") or [])
        try:
            _sil = float((context.get("social_presence") or {}).get("silence_s") or 1e9)
        except Exception:
            _sil = 1e9
        if _sil >= 600:
            cached = [p for p in cached
                      if not (isinstance(p, dict) and p.get("type") == "speak"
                              and str(p.get("description", "")).startswith("Vocalize intention"))]
        return cached

    tl = topic.lower()
    neutral_triggers = {
        "beliefs are stable", "no change needed", "in alignment",
        "nothing to change", "no contradiction", "no action needed",
        "stable", "unchanged", "no meaningful update"
    }
    if any(t in tl for t in neutral_triggers):
        log_activity(f"⏭️ Skipping behavior generation: reflection is neutral ('{topic}')")
        return []
    if "unspecified" in tl or "unknown" in tl:
        log_activity(f"⚠️ Skipping behavior generation due to vague reflection topic: '{topic}'")
        return []

    timestamp = now_iso_z()

    # 2) Clarification questions → propose asking the user
    user_display = context.get("user_display_name") or context.get("user_name") or "the user"
    clarification_prompt = (
        "You are an autonomous agent. Given this goal or topic:\n\n"
        f"'{topic}'\n\n"
        f"List any specific questions you would need answered by {user_display} to fully understand the "
        "requirements, constraints, or context before taking action. Be concise. "
        "Return ONLY a JSON list (array) of strings."
    )
    clarification_raw = llm_ok(generate_response(clarification_prompt, config={"expect_json": True}), "behavior_generation")
    clarification_questions = _coerce_list(safe_extract_json(clarification_raw, default=[]))

    if clarification_questions:
        log_private(f"❓ Generated clarification questions: {clarification_questions}")
        proposals = [{
            "type": "ask_user",
            "content": q,
            "urgency": 0.99,
            "description": "Clarification requested before proceeding",
        } for q in clarification_questions]
        context["_behavior_sig"] = sig
        context["behavior_proposals"] = proposals
        return proposals

    # 3) Decompose goal (read-only)
    decompose_prompt = (
        "You are an autonomous planner. Given this goal:\n\n"
        f"'{topic}'\n\n"
        "Break it down into 3–7 concrete subgoals or actionable tasks needed to accomplish it. "
        "Return ONLY a JSON list (array) of strings."
    )
    subgoals_raw = llm_ok(generate_response(decompose_prompt, config={"expect_json": True}), "behavior_generation")
    subgoals = _coerce_list(safe_extract_json(subgoals_raw, default=[]))

    # 4) Justification (read-only)
    justification_prompt = (
        "Given the focus goal or topic:\n\n"
        f"'{topic}'\n\n"
        "Generate a thoughtful, personal justification for taking action. Make it sincere and motivating, "
        "explaining why this compels growth and progress."
    )
    justification = (llm_ok(generate_response(justification_prompt), "behavior_generation") or "").strip()
    if not justification:
        justification = (
            f"In light of recent reflections on '{topic}', "
            "this action is a gesture toward becoming more than I was."
        )

    # 5) Pick the subgoal this behavior is about.
    #
    # SECURITY / Phase 5 (Option A, function_selection_fix_v2.md §5b): we no
    # longer synthesize a Python stub and propose execute_python_code to run it.
    # The stub only ever appended one thought to working memory, so it is replaced
    # by a structured append_thought effect (built below). This removes the bare
    # in-process exec path entirely AND moots the explore_* stub generation at its
    # source (the §2.4 root cause) — no .py file is written, so no corrupted
    # explore_* defs can be auto-discovered into the cognition pool.
    subgoal_desc = subgoals[0] if subgoals else topic

    # 6) Build proposals (no side-effects)
    proposals: List[Dict[str, Any]] = []

    # Propose speaking intention — but only to an actual audience, and only
    # once per intention. This unconditional proposal produced 365+ of the last
    # 500 utterances ("I'm acting on my goal to grow and accomplish: <step>"),
    # spoken to an empty room on every cycle. Self-narration without a listener
    # belongs in the private log (already written above), not the voice.
    _announce = f"I'm acting on my goal to grow and accomplish: {subgoal_desc}"
    try:
        _silence_s = float((context.get("social_presence") or {}).get("silence_s") or 1e9)
    except Exception:
        _silence_s = 1e9
    if _silence_s < 600 and context.get("_last_intent_announced") != _announce:
        context["_last_intent_announced"] = _announce
        proposals.append({
            "type": "speak",
            "content": _announce,
            "urgency": 0.65,
            "description": "Vocalize intention to evolve",
        })
    else:
        log_private(f"[behavior_generation] intent (unvoiced): {subgoal_desc[:120]}")

    # Propose updating proposed goals (action gate writes full merged list).
    # The file is created here rather than by the gate's dynamic update_file
    # path, so the constant has a visible writer (map-drift fix, audit §7).
    try:
        ensure_files([PROPOSED_GOALS])
        existing = load_json(PROPOSED_GOALS, default_type=list)
        if not isinstance(existing, list):
            existing = []
    except Exception:
        existing = []

    new_items = []
    for sg in subgoals:
        goal_text = f"Accomplish: {sg}"
        if not any(isinstance(g, dict) and g.get("goal") == goal_text for g in existing):
            new_items.append({
                "goal": goal_text,
                "reason": justification,
                "source": "autonomous_decomposition",
                "created_at": timestamp,
            })

    if new_items:
        merged = existing + new_items
        proposals.append({
            "type": "update_file",
            "path": str(PROPOSED_GOALS),
            "data": merged,
            "urgency": 0.70,
            "description": "Save proposed subgoals to disk",
        })

    # Propose creating a few concrete goals
    for sg in subgoals[:3]:
        goal_text = f"Accomplish: {sg}"
        proposals.append({
            "type": "set_goal",
            "content": {"name": goal_text, "tier": "short_term"},
            "urgency": 0.68,
            "description": f"Create actionable goal: {sg}",
        })

    # Propose recording an exploratory thought (Phase 5 / Option A). Structured,
    # data-only effect that REPLACES the old write-a-stub + execute_python_code
    # pair — the stub only appended this same thought to working memory, so no
    # code execution was ever needed.
    proposals.append({
        "type": "append_thought",
        "content": f"Exploring autonomous insight related to: {subgoal_desc}",
        "thought_type": "autonomous_behavior",
        "urgency": 0.76,
        "description": f"Record an exploratory thought about: {subgoal_desc}",
    })

    # Cache & return
    context["_behavior_sig"] = sig
    context["behavior_proposals"] = proposals
    return proposals
