# cognition/self_generated/autogenerated_thoughts.py
#
# Orrin thinks things without being asked.
#
# A spontaneous thought is what surfaces when you're not deliberately
# thinking about anything specific — arising from emotional state, unresolved
# tensions, suppressed impulses, half-formed connections. Different from
# reflection (which examines) and planning (which decides) — this just arrives.
#
# Rate-limited and probabilistic. Strong emotional states lower the threshold.
# Writes to working memory. Whether it gets spoken is the speaker's decision.

from __future__ import annotations
from brain.core.runtime_log import get_logger

import random
import time
from typing import Any, Dict, Optional

from brain.utils.log import log_private
from brain.utils.json_utils import load_json
from brain.cog_memory.working_memory import update_working_memory
from brain.paths import WORKING_MEMORY_FILE
from brain.utils.llm_gate import llm_callable_by
_log = get_logger(__name__)


def _lexicalize_action(fn: str) -> str:
    """Turn an internal function name into plain words for a thought —
    'seek_novelty' → 'seek novelty', 'reflect_on_affect' → 'reflect on affect'.
    Surface realization of a real signal, not a canned phrase."""
    name = (fn or "").strip().lower()
    for pre in ("generate_", "attempt_", "assess_", "do_", "run_"):
        if name.startswith(pre):
            name = name[len(pre):]
            break
    return name.replace("_", " ").strip()


def _is_speakable(text: str) -> bool:
    """True for natural prose — not instrumentation/bracket-soup. Keeps log lines
    and telemetry out of a thought (and out of the language corpus it feeds)."""
    s = (text or "").strip()
    if len(s) < 15 or s.count("[") > 1 or "{" in s or '":' in s:
        return False
    alpha = sum(c.isalpha() for c in s)
    return alpha >= max(10, int(len(s) * 0.5))


def _compose_spontaneous_thought(
    emo: Dict[str, Any],
    suppressed: list,
    conflicts: list,
    lifetime: Dict[str, Any],
    recent_snippets: list,
    goal_text: str,
) -> Optional[str]:
    """Compose a spontaneous thought from Orrin's CURRENT state — not a canned
    phrase. A thought is what surfaces when not deliberately thinking: an
    unresolved tension, a suppressed want, a half-formed connection, or the
    felt state itself (the four sources named in the module docstring). We rank
    the live signals by how much generative pressure they carry and surface the
    hottest one, grounding it in real content (the conflict's own words, the
    lexicalized want, an actual memory) and colouring it with the humanized felt
    state. Returns None when nothing is actually pressing — silence is honest;
    we never emit filler.

    Surface realization is hand-rolled here for now; once the native LM is fluent
    it should generate this narration itself (see acquisition.narrate_experience).
    """
    # Humanized felt state — grounded affect prose, never a raw signal name.
    try:
        from brain.control_signals.signal_summary import describe_dominant_affect
        feel = (describe_dominant_affect(emo) or "").strip()
    except Exception:
        feel = ""
    has_feel = bool(feel) and "hard to name" not in feel and not feel.startswith("quiet")

    # Candidate 1 — unresolved drive tension (highest generative pressure).
    if conflicts and isinstance(conflicts, list):
        hot = max(
            (c for c in conflicts if isinstance(c, dict) and c.get("label")),
            key=lambda c: float(c.get("a_strength", 0) or 0) + float(c.get("b_strength", 0) or 0),
            default=None,
        )
        if hot:
            label = str(hot["label"]).strip()
            tail = f" Underneath it, {feel}." if has_feel else ""
            return f"Something in me {label}, and something else won't let that be the whole story.{tail}"

    # Candidate 2 — a suppressed want (something pulled for but held back).
    if suppressed and isinstance(suppressed, list):
        hottest = max(
            (s for s in suppressed if isinstance(s, dict) and s.get("wanted")),
            key=lambda s: float(s.get("intensity", 0) or 0),
            default=None,
        )
        if hottest:
            want = _lexicalize_action(str(hottest["wanted"]))
            if want:
                tail = f" It still sits with me — {feel}." if has_feel else ""
                return f"Part of me wanted to {want}, and I didn't.{tail}"

    # Candidate 3 — a half-formed connection between two things still in mind.
    speakable = [s.strip() for s in (recent_snippets or []) if _is_speakable(s)]
    if len(speakable) >= 2:
        a, b = speakable[-1], speakable[-2]
        return f"I keep setting these next to each other: \"{a}\" and \"{b}\". I'm not sure yet what connects them."

    # Candidate 4 — the felt state itself, anchored to whatever's nearest.
    if has_feel:
        if speakable:
            return f"{feel[0].upper() + feel[1:]} — and \"{speakable[-1]}\" is still turning over in me."
        if goal_text:
            return f"{feel[0].upper() + feel[1:]}, even with {goal_text} in front of me."
        return feel[0].upper() + feel[1:] + "."

    # Nothing is actually pressing — silence is the honest output.
    return None


_THOUGHT_COOLDOWN_S   = 1200.0   # 20 minutes minimum between thoughts
_BASE_PROBABILITY     = 0.12     # chance when cooldown clears and state is calm
_ELEVATED_PROBABILITY = 0.38     # chance when emotional intensity is high

_last_thought_ts: float = 0.0


def maybe_generate_thought(context: Dict[str, Any]) -> Optional[str]:
    """
    Called each cycle from finalize.py.
    Returns the thought string if one was generated, else None.
    """
    global _last_thought_ts
    now = time.time()
    if now - _last_thought_ts < _THOUGHT_COOLDOWN_S:
        return None
    try:
        return _generate(context, now)
    except Exception as e:
        log_private(f"[autogenerated_thought] error: {e}")
        return None


def _generate(context: Dict[str, Any], now: float) -> Optional[str]:
    global _last_thought_ts

    emo = context.get("affect_state") or {}
    core = emo.get("core_signals") or emo
    if not isinstance(core, dict):
        return None

    # Find dominant emotion and its intensity
    dominant, intensity = "neutral", 0.0
    for k, v in core.items():
        if isinstance(v, (int, float)) and float(v) > intensity:
            intensity = float(v)
            dominant = k

    # Probabilistic gate
    prob = _ELEVATED_PROBABILITY if intensity >= 0.50 else _BASE_PROBABILITY
    if random.random() > prob:
        return None

    # Gather lean context — avoid flooding the prompt
    wm = load_json(WORKING_MEMORY_FILE, default_type=list) or []
    recent_snippets = [
        str(e.get("content", ""))[:80]
        for e in (wm[-8:] if len(wm) > 8 else wm)
        if isinstance(e, dict)
        and not str(e.get("content", "")).startswith(("🧠", "✅", "⚠️", "⏳", "[deadline]"))
    ]
    recent_text = "\n".join(f"- {s}" for s in recent_snippets if s.strip())

    goal = context.get("committed_goal") or {}
    goal_text = (goal.get("title") or "") if isinstance(goal, dict) else ""

    # Suppressed impulse — something wanted but not done
    suppressed = context.get("_suppressed_impulses") or []
    suppressed_note = ""
    if suppressed and isinstance(suppressed, list):
        hottest = max(suppressed, key=lambda x: float(x.get("intensity") or 0), default={})
        if hottest.get("wanted"):
            suppressed_note = f"Part of me wanted to {hottest['wanted']!r} but something held back."

    # Lifetime phase — colors late-life thoughts
    lifetime = context.get("_lifetime") or {}
    mort_note = ""
    if lifetime.get("phase") in ("late", "terminal"):
        days = lifetime.get("days_remaining_felt", 0)
        mort_note = f"I'm aware I have roughly {days:.0f} days left."

    # Demand conflicts — unresolved tensions are generative
    conflicts = context.get("_drive_conflicts") or []
    conflict_note = ""
    if conflicts and isinstance(conflicts, list):
        hot = conflicts[0] if conflicts else {}
        if hot.get("label"):
            conflict_note = f"I'm caught between: {hot['label']}."

    if not llm_callable_by("autogenerated_thought"):
        # Symbolic: compose the thought from current state (drive tension,
        # suppressed want, half-formed connection, or felt state). None when
        # nothing is pressing — no filler, never a vocabulary template.
        thought = _compose_spontaneous_thought(
            emo=emo,
            suppressed=suppressed,
            conflicts=conflicts,
            lifetime=lifetime,
            recent_snippets=recent_snippets,
            goal_text=goal_text,
        )
        if not thought:
            return None

        update_working_memory({
            "content": thought,
            "event_type": "spontaneous_thought",
            "importance": 2,
            "priority": 2,
        })
        _last_thought_ts = now
        log_private(f"[autogenerated_thought] symbolic ({dominant}): {thought[:100]}")
        return thought

    from brain.utils.generate_response import generate_response, llm_ok

    prompt_parts = [
        "You are Orrin. A thought has surfaced — not because you chose to think it, but because it arose.",
        f"\nCurrent emotional state: {dominant} (intensity {intensity:.2f})",
    ]
    if recent_text:
        prompt_parts.append(f"\nWhat's been on your mind:\n{recent_text}")
    if goal_text:
        prompt_parts.append(f"\nActive goal: {goal_text}")
    if suppressed_note:
        prompt_parts.append(f"\n{suppressed_note}")
    if conflict_note:
        prompt_parts.append(f"\n{conflict_note}")
    if mort_note:
        prompt_parts.append(f"\n{mort_note}")
    prompt_parts.append(
        "\n\nGenerate ONE spontaneous thought — 1-2 sentences. Not a plan, not a reflection, "
        "not a decision. Just what arises: a connection you just noticed, something unresolved, "
        "a question, a half-formed feeling. Write in first person as Orrin."
    )

    thought = llm_ok(generate_response("".join(prompt_parts), caller="autogenerated_thought"), "autogenerated")
    if not thought or len(thought.strip()) < 10:
        return None

    thought = thought.strip()
    if len(thought) > 300:
        thought = thought[:297] + "..."

    update_working_memory({
        "content": thought,
        "event_type": "spontaneous_thought",
        "importance": 2,
        "priority": 2,
    })

    _last_thought_ts = now
    log_private(f"[autogenerated_thought] {thought[:100]}")
    return thought


from datetime import datetime, timezone
from brain.utils.append import append_to_json

def explore_write_a_cognitive_function_or_tool_that_improves_something():
    """
    Autogenerated by Orrin to deepen understanding of: "Reflect on what's been tried"
    Instead of printing, this function appends an internal thought to working memory.
    """
    thought = {
        "content": "Exploring autonomous insight related to: Reflect on what's been tried",
        "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00","Z"),
        "type": "autonomous_behavior"
    }
    append_to_json(WORKING_MEMORY_FILE, thought)
