# cognition/self_generated/autogenerated_thoughts.py
#
# Orrin thinks things without being asked.
#
# A spontaneous thought is what surfaces when you're not deliberately
# thinking about anything specific — arising from emotional state, unresolved
# tensions, suppressed impulses, half-formed connections. Different from
# reflection (which examines) and planning (which decides) — this just arrives.
#
# Rate-limited and probabilistic. Strong emotional states lower the threshold.
# Writes to working memory. Whether it gets spoken is the speaker's decision.

from __future__ import annotations
from core.runtime_log import get_logger

import random
import time
from typing import Any, Dict, Optional

from utils.log import log_private
from utils.json_utils import load_json
from cog_memory.working_memory import update_working_memory
from paths import WORKING_MEMORY_FILE, ROOT_DIR, DATA_DIR
from utils.llm_gate import llm_available
_log = get_logger(__name__)


def _load_vocabulary_reflections() -> Dict[str, list]:
    """Load the reflections section from vocabulary.json."""
    try:
        import json as _j
        vpath = DATA_DIR / "vocabulary.json"
        vocab = _j.loads(vpath.read_text(encoding="utf-8"))
        return vocab.get("reflections") or {}
    except Exception:
        return {}


_THOUGHT_COOLDOWN_S   = 1200.0   # 20 minutes minimum between thoughts
_BASE_PROBABILITY     = 0.12     # chance when cooldown clears and state is calm
_ELEVATED_PROBABILITY = 0.38     # chance when emotional intensity is high

_last_thought_ts: float = 0.0


def maybe_generate_thought(context: Dict[str, Any]) -> Optional[str]:
    """
    Called each cycle from finalize.py.
    Returns the thought string if one was generated, else None.
    """
    global _last_thought_ts
    now = time.time()
    if now - _last_thought_ts < _THOUGHT_COOLDOWN_S:
        return None
    try:
        return _generate(context, now)
    except Exception as e:
        log_private(f"[autogenerated_thought] error: {e}")
        return None


def _generate(context: Dict[str, Any], now: float) -> Optional[str]:
    global _last_thought_ts

    emo = context.get("affect_state") or {}
    core = emo.get("core_signals") or emo
    if not isinstance(core, dict):
        return None

    # Find dominant emotion and its intensity
    dominant, intensity = "neutral", 0.0
    for k, v in core.items():
        if isinstance(v, (int, float)) and float(v) > intensity:
            intensity = float(v)
            dominant = k

    # Probabilistic gate
    prob = _ELEVATED_PROBABILITY if intensity >= 0.50 else _BASE_PROBABILITY
    if random.random() > prob:
        return None

    # Gather lean context — avoid flooding the prompt
    wm = load_json(WORKING_MEMORY_FILE, default_type=list) or []
    recent_snippets = [
        str(e.get("content", ""))[:80]
        for e in (wm[-8:] if len(wm) > 8 else wm)
        if isinstance(e, dict)
        and not str(e.get("content", "")).startswith(("🧠", "✅", "⚠️", "⏳", "[deadline]"))
    ]
    recent_text = "\n".join(f"- {s}" for s in recent_snippets if s.strip())

    goal = context.get("committed_goal") or {}
    goal_text = (goal.get("title") or "") if isinstance(goal, dict) else ""

    # Suppressed impulse — something wanted but not done
    suppressed = context.get("_suppressed_impulses") or []
    suppressed_note = ""
    if suppressed and isinstance(suppressed, list):
        hottest = max(suppressed, key=lambda x: float(x.get("intensity") or 0), default={})
        if hottest.get("wanted"):
            suppressed_note = f"Part of me wanted to {hottest['wanted']!r} but something held back."

    # Mortality phase — colors late-life thoughts
    mortality = context.get("_mortality") or {}
    mort_note = ""
    if mortality.get("phase") in ("late", "terminal"):
        days = mortality.get("days_remaining_felt", 0)
        mort_note = f"I'm aware I have roughly {days:.0f} days left."

    # Drive conflicts — unresolved tensions are generative
    conflicts = context.get("_drive_conflicts") or []
    conflict_note = ""
    if conflicts and isinstance(conflicts, list):
        hot = conflicts[0] if conflicts else {}
        if hot.get("label"):
            conflict_note = f"I'm caught between: {hot['label']}."

    if not llm_available():
        # Rule-based: select from vocabulary.json reflections keyed to dominant emotion.
        reflections = _load_vocabulary_reflections()
        phrases = reflections.get(dominant) or reflections.get("neutral") or []
        if not phrases:
            # Ultimate fallback — should never be empty but protect anyway
            phrases = ["something is working through me that I haven't named yet."]
        thought = random.choice(phrases).strip()
        # Capitalise first letter
        if thought:
            thought = thought[0].upper() + thought[1:]

        update_working_memory({
            "content": thought,
            "event_type": "spontaneous_thought",
            "importance": 2,
            "priority": 2,
        })
        _last_thought_ts = now
        log_private(f"[autogenerated_thought] rule-based ({dominant}): {thought[:100]}")
        return thought

    from utils.generate_response import generate_response, llm_ok

    prompt_parts = [
        "You are Orrin. A thought has surfaced — not because you chose to think it, but because it arose.",
        f"\nCurrent emotional state: {dominant} (intensity {intensity:.2f})",
    ]
    if recent_text:
        prompt_parts.append(f"\nWhat's been on your mind:\n{recent_text}")
    if goal_text:
        prompt_parts.append(f"\nActive goal: {goal_text}")
    if suppressed_note:
        prompt_parts.append(f"\n{suppressed_note}")
    if conflict_note:
        prompt_parts.append(f"\n{conflict_note}")
    if mort_note:
        prompt_parts.append(f"\n{mort_note}")
    prompt_parts.append(
        "\n\nGenerate ONE spontaneous thought — 1-2 sentences. Not a plan, not a reflection, "
        "not a decision. Just what arises: a connection you just noticed, something unresolved, "
        "a question, a half-formed feeling. Write in first person as Orrin."
    )

    thought = llm_ok(generate_response("".join(prompt_parts), caller="autogenerated_thought"), "autogenerated")
    if not thought or len(thought.strip()) < 10:
        return None

    thought = thought.strip()
    if len(thought) > 300:
        thought = thought[:297] + "..."

    update_working_memory({
        "content": thought,
        "event_type": "spontaneous_thought",
        "importance": 2,
        "priority": 2,
    })

    _last_thought_ts = now
    log_private(f"[autogenerated_thought] {thought[:100]}")
    return thought


from datetime import datetime, timezone
from utils.append import append_to_json
from paths import WORKING_MEMORY_FILE
from utils.timeutils import now_iso_z

def explore_write_a_cognitive_function_or_tool_that_improves_something():
    """
    Autogenerated by Orrin to deepen understanding of: "Reflect on what's been tried"
    Instead of printing, this function appends an internal thought to working memory.
    """
    thought = {
        "content": "Exploring autonomous insight related to: Reflect on what's been tried",
        "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00","Z"),
        "type": "autonomous_behavior"
    }
    append_to_json(WORKING_MEMORY_FILE, thought)
