# registry/function_catalog.py
#
# Builds a "map of Orrin's mind": every registered cognitive (and behavioral)
# function tagged with the subsystem it belongs to, where its source lives, and a
# one-line summary. Drives the Cognitive Map UI (zoomable code map + click-to-read).
#
# Pure introspection over the live registries — no behaviour change.
from __future__ import annotations
from brain.core.runtime_log import get_logger

import inspect
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

_log = get_logger(__name__)

# repo root = parent of brain/ (brain/registry/function_catalog.py → parents[2])
_REPO_ROOT = Path(__file__).resolve().parents[2]

# Map a source path fragment → human subsystem. First match wins (order matters:
# more specific fragments first).
_SUBSYSTEM_RULES: Tuple[Tuple[str, str], ...] = (
    ("cognition/language", "Language"),
    ("cognition/perception", "Perception"),
    ("perception", "Perception"),
    ("look_outward", "Perception"),
    # self-generated thoughts/functions — the biggest single cluster
    ("self_generated", "Generated"),
    ("autogenerated", "Generated"),
    # self-improvement / extension
    ("finetuning", "Self-Improvement"),
    ("self_extension", "Self-Improvement"),
    ("skill_synthesis", "Self-Improvement"),
    ("self_improvement", "Self-Improvement"),
    ("cognition/maintenance", "Self-Improvement"),
    ("cognition/innovation", "Self-Improvement"),
    # experimentation / sandbox
    ("sandbox", "Experimentation"),
    ("experiment", "Experimentation"),
    # memory (cognition-side stores too)
    ("cog_memory", "Memory"),
    ("/memory", "Memory"),
    ("concept_memory", "Memory"),
    ("associative_memory", "Memory"),
    ("concept_formation", "Memory"),
    ("world_model", "Memory"),
    # reflection / metacognition / idle consolidation
    ("cognition/reflection", "Reflection"),
    ("metacog", "Reflection"),
    ("cognition/idle_consolidation", "Reflection"),
    ("threads", "Dialogue"),
    ("awaiting_response", "Dialogue"),
    # self / identity / values / will
    ("cognition/self_state", "Self"),
    ("identity", "Self"),
    ("opinions", "Values"),
    ("will", "Values"),
    ("volition", "Values"),
    ("value", "Values"),
    ("privacy", "Values"),
    ("body_sense", "Body"),
    # planning / goals
    ("cognition/planning", "Planning"),
    ("goal_competition", "Planning"),
    ("intrinsic_goals", "Planning"),
    ("/goals", "Planning"),
    # prediction / learning
    ("symbolic", "Prediction/Learning"),
    ("prediction", "Prediction/Learning"),
    ("causal", "Prediction/Learning"),
    ("knowledge", "Prediction/Learning"),
    # control / regulation
    ("calibration", "Control"),
    ("reward_calibrator", "Control"),
    ("temporal_pressure", "Control"),
    ("cognitive_cost", "Control"),
    ("habituation", "Control"),
    ("attention", "Control"),
    ("global_workspace", "Control"),
    ("inhibition", "Control"),
    # affect
    ("affect", "Affect"),
    ("motivation", "Affect"),
    ("emotion", "Affect"),
    # curiosity
    ("wonder", "Curiosity"),
    ("seek_novelty", "Curiosity"),
    ("ambient", "Curiosity"),
    # action / behavior / output
    ("behavior", "Action"),
    ("action_gate", "Action"),
    ("speech", "Action"),
    ("think", "Action"),
    ("cognition/", "Cognition"),
)


def _subsystem_for(rel_path: str) -> str:
    p = rel_path.replace("\\", "/").lower()
    for frag, name in _SUBSYSTEM_RULES:
        if frag in p:
            return name
    return "Other"


def _unwrap(fn: Callable) -> Callable:
    try:
        return inspect.unwrap(fn)
    except ValueError:  # intentional: unwrap cycle → use wrapper as-is
        return fn


def _introspect(fn: Callable) -> Optional[Dict[str, Any]]:
    fn = _unwrap(fn)
    try:
        src_file = inspect.getsourcefile(fn) or inspect.getfile(fn)
    except (TypeError, OSError):
        return None
    if not src_file:
        return None
    try:
        rel = str(Path(src_file).resolve().relative_to(_REPO_ROOT))
    except Exception:
        rel = Path(src_file).name
    lineno = getattr(getattr(fn, "__code__", None), "co_firstlineno", 0) or 0
    endline = lineno
    try:
        lines, start = inspect.getsourcelines(fn)
        lineno = start or lineno
        endline = (start or lineno) + max(0, len(lines) - 1)
    except (TypeError, OSError):
        pass
    doc = (inspect.getdoc(fn) or "").strip()
    summary = doc.splitlines()[0].strip() if doc else ""
    return {"file": rel, "lineno": int(lineno), "endline": int(endline), "summary": summary[:200]}


def _iter_registry() -> List[Tuple[str, Callable, str]]:
    """Yield (name, callable, kind) for cognitive + behavioral functions."""
    out: List[Tuple[str, Callable, str]] = []
    try:
        from brain.registry.cognition_registry import COGNITIVE_FUNCTIONS
        for name, meta in (COGNITIVE_FUNCTIONS or {}).items():
            fn = meta.get("function") if isinstance(meta, dict) else meta
            if callable(fn) and isinstance(name, str):
                out.append((name, fn, "cognition"))
    except Exception as e:
        _log.warning("catalog: cognition registry unavailable: %s", e)
    try:
        from brain.registry.behavior_registry import BEHAVIORAL_FUNCTIONS
        for name, meta in (BEHAVIORAL_FUNCTIONS or {}).items():
            fn = meta.get("function") if isinstance(meta, dict) else meta
            if callable(fn) and isinstance(name, str):
                out.append((name, fn, "behavior"))
    except Exception as e:
        _log.warning("catalog: behavior registry unavailable: %s", e)
    return out


_CACHE: Optional[Dict[str, Any]] = None


def build_catalog(force: bool = False) -> Dict[str, Any]:
    """
    Return {"functions": {name: {subsystem, file, lineno, endline, summary, kind}},
            "subsystems": {subsystem: [names...]}}. Cached after first build.
    """
    global _CACHE
    if _CACHE is not None and not force:
        return _CACHE
    functions: Dict[str, Any] = {}
    subsystems: Dict[str, List[str]] = {}
    for name, fn, kind in _iter_registry():
        if name in functions:
            continue
        info = _introspect(fn)
        if not info:
            continue
        sub = _subsystem_for(info["file"])
        functions[name] = {**info, "subsystem": sub, "kind": kind, "name": name}
        subsystems.setdefault(sub, []).append(name)
    for names in subsystems.values():
        names.sort()
    _CACHE = {"functions": functions, "subsystems": subsystems}
    return _CACHE
