"""
backend/server/generate_telemetry_ts.py — telemetry wire-contract codegen (Phase 5.2).

Renders `frontend/src/lib/telemetry.gen.ts` (zod schemas + inferred TypeScript
types) from the pydantic models in `schema.py`, which are the single source of
truth for the FE↔BE telemetry boundary. This replaces the old hand-mirrored
`types.ts` block, so the frontend types can no longer silently drift from the
backend contract.

The same generated file delivers BOTH contract layers:
  * static  — `export type X = z.infer<typeof XSchema>` types the UI code;
  * runtime — the zod `XSchema` validates frames at the browser boundary.

Run via `make telemetry-types` (or `python -m backend.server.generate_telemetry_ts`).
`tests/observability_tests/telemetry_codegen_test.py` re-renders in-memory and
fails if the committed file is stale, so a schema change without regen breaks CI.

The generator supports the deliberately small type subset the wire models use:
str / int / float / bool / Any, Optional[X], List[X], Dict[str, X],
Literal[...], Union[...], and nested wire BaseModels. Anything outside that
subset raises here (loudly) rather than emitting silently-wrong TS.
"""
from __future__ import annotations

import json
import typing
from pathlib import Path
from typing import Any, List, Literal, Tuple, Union, get_args, get_origin

from pydantic import BaseModel

from backend.server.schema import WIRE_MODELS

_OUT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "lib" / "telemetry.gen.ts"
_NONE = type(None)


def _map_type(ann: Any) -> Tuple[str, str]:
    """Map a (non-Optional) annotation to (zod_expr, ts_type)."""
    if ann is Any:
        return "z.unknown()", "unknown"
    if ann is str:
        return "z.string()", "string"
    if ann is bool:
        return "z.boolean()", "boolean"
    if ann in (int, float):
        return "z.number()", "number"
    if isinstance(ann, type) and issubclass(ann, BaseModel):
        return f"{ann.__name__}Schema", ann.__name__

    origin = get_origin(ann)
    if origin is Literal:
        args = get_args(ann)
        if len(args) == 1:
            lit = json.dumps(args[0])
            return f"z.literal({lit})", lit
        zod = "z.enum([" + ", ".join(json.dumps(a) for a in args) + "])"
        ts = " | ".join(json.dumps(a) for a in args)
        return zod, ts
    if origin is Union:
        non_none = [a for a in get_args(ann) if a is not _NONE]
        parts = [_map_type(a) for a in non_none]
        if len(parts) == 1:
            return parts[0]
        zod = "z.union([" + ", ".join(z for z, _ in parts) + "])"
        ts = " | ".join(t for _, t in parts)
        return zod, ts
    if origin in (list, List):
        z, t = _map_type(get_args(ann)[0])
        return f"z.array({z})", f"{t}[]"
    if origin in (dict, typing.Dict):
        _k, v = get_args(ann)
        zv, tv = _map_type(v)
        return f"z.record(z.string(), {zv})", f"Record<string, {tv}>"

    raise TypeError(f"telemetry codegen: unsupported annotation {ann!r}")


def _field(ann: Any) -> Tuple[str, str]:
    """Map a field annotation to (zod_expr, ts_type), unwrapping Optional[...] to
    a `.nullable()` zod modifier + a `| null` TS union."""
    if get_origin(ann) is Union and _NONE in get_args(ann):
        non_none = tuple(a for a in get_args(ann) if a is not _NONE)
        inner = non_none[0] if len(non_none) == 1 else Union[non_none]
        z, t = _map_type(inner)
        return f"{z}.nullable()", f"{t} | null"
    return _map_type(ann)


def _render_model(model: type[BaseModel]) -> str:
    lines = [f"export const {model.__name__}Schema = z.looseObject({{"]
    for name, info in model.model_fields.items():
        prop = info.alias or name
        zod, _ts = _field(info.annotation)
        # Every wire field is optional: producers send partial frames.
        lines.append(f"  {json.dumps(prop)}: {zod}.optional(),")
    lines.append("});")
    lines.append(f"export type {model.__name__} = z.infer<typeof {model.__name__}Schema>;")
    return "\n".join(lines)


def render_ts() -> str:
    """Render the full telemetry.gen.ts contents (deterministic)."""
    header = (
        "// AUTO-GENERATED by backend/server/generate_telemetry_ts.py — DO NOT EDIT.\n"
        "// Source of truth: backend/server/schema.py. Regenerate: `make telemetry-types`.\n"
        "// Drift is caught by tests/observability_tests/telemetry_codegen_test.py.\n"
        'import { z } from "zod";\n'
    )
    blocks = [_render_model(m) for m in WIRE_MODELS]
    return header + "\n" + "\n\n".join(blocks) + "\n"


def main() -> None:
    _OUT.write_text(render_ts(), encoding="utf-8")
    print(f"wrote {_OUT.relative_to(Path(__file__).resolve().parents[2])}")


if __name__ == "__main__":
    main()
