// AUTO-GENERATED by backend/server/generate_telemetry_ts.py — DO NOT EDIT.
// Source of truth: backend/server/schema.py. Regenerate: `make telemetry-types`.
// Drift is caught by tests/observability_tests/telemetry_codegen_test.py.
import { z } from "zod";

export const AffectFrameSchema = z.looseObject({
  "valence": z.number().nullable().optional(),
  "arousal": z.number().nullable().optional(),
  "homeostasis": z.number().nullable().optional(),
  "extra": z.record(z.string(), z.number()).optional(),
});
export type AffectFrame = z.infer<typeof AffectFrameSchema>;

export const MemoryRecordSchema = z.looseObject({
  "id": z.string().nullable().optional(),
  "op": z.enum(["read", "write"]).optional(),
  "store": z.string().optional(),
  "key": z.string().optional(),
  "summary": z.string().optional(),
  "salience": z.number().nullable().optional(),
  "ts": z.number().nullable().optional(),
});
export type MemoryRecord = z.infer<typeof MemoryRecordSchema>;

export const LogLineSchema = z.looseObject({
  "level": z.enum(["debug", "info", "warn", "error", "critical"]).optional(),
  "source": z.string().optional(),
  "message": z.string().optional(),
  "ts": z.number().nullable().optional(),
});
export type LogLine = z.infer<typeof LogLineSchema>;

export const GoalSchema = z.looseObject({
  "id": z.string().nullable().optional(),
  "title": z.string().optional(),
  "status": z.string().optional(),
  "tier": z.string().nullable().optional(),
  "priority": z.union([z.number(), z.string()]).nullable().optional(),
  "tags": z.array(z.string()).nullable().optional(),
  "steps_done": z.number().nullable().optional(),
  "steps_total": z.number().nullable().optional(),
  "current_step": z.string().nullable().optional(),
  "active": z.boolean().nullable().optional(),
  "serves": z.string().nullable().optional(),
  "aspiration": z.boolean().nullable().optional(),
});
export type Goal = z.infer<typeof GoalSchema>;

export const FnEventSchema = z.looseObject({
  "fn": z.string().optional(),
  "cycle": z.number().nullable().optional(),
  "reward": z.number().nullable().optional(),
  "lane": z.string().nullable().optional(),
});
export type FnEvent = z.infer<typeof FnEventSchema>;

export const TelemetryFrameSchema = z.looseObject({
  "active_node": z.string().nullable().optional(),
  "node_status": z.record(z.string(), z.string()).optional(),
  "narrative": z.string().nullable().optional(),
  "affect": AffectFrameSchema.nullable().optional(),
  "memory": z.array(MemoryRecordSchema).optional(),
  "logs": z.array(LogLineSchema).optional(),
  "metrics": z.record(z.string(), z.number()).optional(),
  "cycle": z.number().nullable().optional(),
  "extra": z.record(z.string(), z.unknown()).optional(),
  "active_fn": z.string().nullable().optional(),
  "active_lane": z.string().nullable().optional(),
  "fn_recent": z.array(FnEventSchema).optional(),
  "catalog": z.record(z.string(), z.unknown()).nullable().optional(),
  "goals": z.array(GoalSchema).optional(),
  "executive": z.record(z.string(), z.unknown()).nullable().optional(),
  "monitor": z.record(z.string(), z.unknown()).nullable().optional(),
  "workspace": z.record(z.string(), z.unknown()).nullable().optional(),
  "interoception": z.record(z.string(), z.unknown()).nullable().optional(),
});
export type TelemetryFrame = z.infer<typeof TelemetryFrameSchema>;
